# This file was generated by GoReleaser. DO NOT EDIT.
cask "routedns" do
  version "1.0.0"

  on_macos do
    on_arm do
      sha256 "9274428003a22a36f55afb8e9acf9c5b80ae7bdeb194f1b5ac22e38b38ab208b"
      url "https://github.com/folbricht/routedns/releases/download/v#{version}/routedns-darwin-arm64"
      binary "routedns-darwin-arm64", target: "routedns"
    end
    on_intel do
      sha256 "8069fa5a042970886446acf558c621c556db86e9d37b497fa13015e7e60c1f48"
      url "https://github.com/folbricht/routedns/releases/download/v#{version}/routedns-darwin-amd64"
      binary "routedns-darwin-amd64", target: "routedns"
    end
  end
  on_linux do
    on_arm do
      sha256 "91f283feafe0e083159523b4918e4e43110e67f89fe8f79e170ff8afd2a91ec1"
      url "https://github.com/folbricht/routedns/releases/download/v#{version}/routedns-linux-arm64"
      binary "routedns-linux-arm64", target: "routedns"
    end
    on_intel do
      sha256 "fed9aa96d3ebef9ad7c48f3e51cdf23771acebe5af09458144ca26aaa1a0e136"
      url "https://github.com/folbricht/routedns/releases/download/v#{version}/routedns-linux-amd64"
      binary "routedns-linux-amd64", target: "routedns"
    end
  end

  name "routedns"
  desc "DNS stub resolver, proxy and router with support for DoT, DoH, DoQ and more"
  homepage "https://github.com/folbricht/routedns"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      Dir.glob("#{staged_path}/routedns*").each do |f|
        system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", f], must_succeed: false
      end
    end
  end

  # No zap stanza required
end
