# This file was generated by GoReleaser. DO NOT EDIT.
cask "routedns" do
  version "0.1.236"

  on_macos do
    on_intel do
      sha256 "f88bc8abc93f9f19756a2264ba9473761e60a750f372f9379adc522e8f257480"
      url "https://github.com/folbricht/routedns/releases/download/v#{version}/routedns-darwin-amd64"
      binary "routedns-darwin-amd64", target: "routedns"
    end
    on_arm do
      sha256 "b5a5aea9581b15c9952147e84339621495a8749759fc4693c39ee3abb4b935e7"
      url "https://github.com/folbricht/routedns/releases/download/v#{version}/routedns-darwin-arm64"
      binary "routedns-darwin-arm64", target: "routedns"
    end
  end

  on_linux do
    on_intel do
      sha256 "72edfddc656e29700ecd3f872902eb7016208bfffb4f9a9f216a27e53d07e83f"
      url "https://github.com/folbricht/routedns/releases/download/v#{version}/routedns-linux-amd64"
      binary "routedns-linux-amd64", target: "routedns"
    end
    on_arm do
      sha256 "95fbe47fd62acbc90343a89d66178f4eb24f3b66dc0bf408a1f99b59472f1840"
      url "https://github.com/folbricht/routedns/releases/download/v#{version}/routedns-linux-arm64"
      binary "routedns-linux-arm64", target: "routedns"
    end
  end

  name "routedns"
  desc "DNS stub resolver, proxy and router with support for DoT, DoH, DoQ and more"
  homepage "https://github.com/folbricht/routedns"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      Dir.glob("#{staged_path}/routedns*").each do |f|
        system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", f], must_succeed: false
      end
    end
  end

  # No zap stanza required

end
