# This file was generated by GoReleaser. DO NOT EDIT.
cask "routedns" do
  version "0.1.245"

  on_macos do
    on_arm do
      sha256 "6e1e2cca1c9fd1f8fe8023c37de9f1b8e40375b56bc404b476975f4e7ba8d031"
      url "https://github.com/folbricht/routedns/releases/download/v#{version}/routedns-darwin-arm64"
      binary "routedns-darwin-arm64", target: "routedns"
    end
    on_intel do
      sha256 "8854128dfc256700e37604a997c7c03e889d8c4f438635531ab90a1e190cba36"
      url "https://github.com/folbricht/routedns/releases/download/v#{version}/routedns-darwin-amd64"
      binary "routedns-darwin-amd64", target: "routedns"
    end
  end
  on_linux do
    on_arm do
      sha256 "f61e9e34e9dbdf08792f935fc3e45ba3171d8e9d73673355f3eac19a672ab2ab"
      url "https://github.com/folbricht/routedns/releases/download/v#{version}/routedns-linux-arm64"
      binary "routedns-linux-arm64", target: "routedns"
    end
    on_intel do
      sha256 "7d50febb648eb1ceac72c9d107f1ac6666722d420d5e9523cb08eaf67fe9a70c"
      url "https://github.com/folbricht/routedns/releases/download/v#{version}/routedns-linux-amd64"
      binary "routedns-linux-amd64", target: "routedns"
    end
  end

  name "routedns"
  desc "DNS stub resolver, proxy and router with support for DoT, DoH, DoQ and more"
  homepage "https://github.com/folbricht/routedns"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      Dir.glob("#{staged_path}/routedns*").each do |f|
        system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", f], must_succeed: false
      end
    end
  end

  # No zap stanza required
end
